spring:
  application:
    name: security
  datasource:
    url: jdbc:mysql://localhost:3306/securitydatabase
    username: root
    password: Dhanush@2002
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8001
