server:
  port: 8222

spring:
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: http://localhost:8001
          predicates:
            - Path=/auth/**

        - id: user-input
          uri: http://localhost:8080
          predicates:
            - Path=/api/inputs/**
          filters:
            - name: JwtAuthFilter
              args:
                allowedRoles: "user"

        - id: cost-estimator-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/cost-estimates/**
          filters:
            - name: JwtAuthFilter
              args:
                allowedRoles: "user"
                  

        - id: material-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/materials/**
          filters:
            - name: JwtAuthFilter
              args:
                allowedRoles: "user,admin"
                  

        - id: construction-service
          uri: http://localhost:9093
          predicates:
            - Path=/api/constructors/**
          filters:
            - name: JwtAuthFilter
              args:
                allowedRoles: "user"
                  

        - id: report-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/reports/**
          filters:
            - name: JwtAuthFilter
              args:
                allowedRoles: "user"
                
